### PR TITLE
Include the test class in the JUnit Description

### LINKED ISSUE #61: Include the test class in the Description
I'm trying to design a JUnit4 Rule and have run into an issue with tests using Burst, because the `Description` passed to my rule returns null from `getTestClass()`.

It looks like [this line](https://github.com/square/burst/blob/dbe2dad/burst-junit4/src/main/java/com/squareup/burst/BurstRunner.java#L45) is the source of the `Description` in question, as it passes a custom string instead of a [`className`](https://junit.org/junit4/javadoc/4.12/org/junit/runner/Description.html#createTestDescription(java.lang.String,%20java.lang.String,%20java.lang.annotation.Annotation...)).

Would Burst be open to fixing this? Something like:

```java
return Description.createTestDescription(
    getTestClass().getJavaClass(),
    getName() + ":" + method.getName(),
    method.getAnnotations());
```

Is sufficient for my use case, though it does change the result of `Description.getDisplayName()`. If that works I'm happy to send a PR, otherwise are there other approaches you might be open to?

### PR DESCRIPTION
**Pull request by dimo414**
Fixes #61

### CODE REVIEW

**Comment by dimo414** [comment]
Travis failure looks unrelated, but I generated this from GitHub's web UI so it'd be nice to see Travis pass before merging.

**Comment by JakeWharton** [comment]
Yes. No one has contributed in a looooong while so the build configuration is stale. I'll fix it here soon and rebase your PR.

**Comment by JakeWharton** [comment]
(Soon == order of days, I'm on paternity leave)

**Comment by JakeWharton** [comment]
OK I fixed the CI build and rebased your change but now there's actual tests failing. I'll try to look later in the week unless you beat me to it.

**Comment by dimo414** [comment]
Yeah, this fix on its own isn't going to work. I'm afraid I don't have the time to dig into this further, but it certainly would be nice if Burst preserved the test class in the description.

**Pull request closed without merging**
